# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
