# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20171117_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('N', 'N')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='travel.UserProfile'),
        ),
    ]
