# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20171117_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.UserProfile'),
        ),
    ]
