# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20171106_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AddField(
            model_name='visit',
            name='location_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='travel.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
