# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20171102_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel.User'),
        ),
    ]
