# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20171106_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
    ]
