# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20171102_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='location_id',
            field=models.ForeignKey(choices=[('o', 'o'), ('b', 'b'), ('j', 'j'), ('e', 'e'), ('c', 'c'), ('t', 't'), ('s', 's')], on_delete=django.db.models.deletion.CASCADE, to='travel.Location'),
        ),
    ]
