# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0006_auto_20171107_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ManyToManyField(default=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
