# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20171102_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='location_id',
            field=models.ForeignKey(choices=[((1, 'RB', 'Minsk', 'square', 'square of freedom'), (1, 'RB', 'Minsk', 'square', 'square of freedom')), ((2, 'RB', 'Minsk', 'square2', 'square of fall'), (2, 'RB', 'Minsk', 'square2', 'square of fall'))], on_delete=django.db.models.deletion.CASCADE, to='travel.Location'),
        ),
    ]
