# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20171103_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
