# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-05 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20171105_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
