# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-05 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20171105_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='user_id',
        ),
    ]
