# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-05 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_remove_visit_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
